version: '3.8'

services:
  api:
    build: .
    container_name: eyeson-back-api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  test:
    build: .
    container_name: eyeson-back-test
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
      - ./pytest.ini:/app/pytest.ini
      - ./.coveragerc:/app/.coveragerc
      - ./requirements.txt:/app/requirements.txt
    environment:
      - PYTHONUNBUFFERED=1
    command: sh -c "pip install --no-cache-dir -r requirements.txt && pytest"
    profiles:
      - test

